export const ALLPRODUCTS_SUCCESS = 'ALLPRODUCTS_SUCCESS';
export const ALLPRODUCTS_FAILED = 'ALLPRODUCTS_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const ADDPRODUCT_SUCCESS = 'ADDPRODUCT_SUCCESS';
export const ADDPRODUCT_FAILED = 'ADDPRODUCT_FAILED';

export const GETVIEWS_SUCCESS = 'GETVIEWS_SUCCESS';
export const GETVIEWS_FAILED = 'GETVIEWS_FAILED';

export const GETPRODUCTDETAILS_SUCCESS= 'GETPRODUCTDETAILS_SUCCESS';
export const GETPRODUCTDETAILS_FAILED = 'GETPRODUCTDETAILS_FAILED';