export const CONSUMER_LOGIN_SUCCESS = 'CONSUMER_LOGIN_SUCCESS';
export const CONSUMER_LOGIN_FAILED = 'CONSUMER_LOGIN_FAILED';

export const CONSUMER_SIGNUP_SUCCESS = 'CONSUMER_SIGNUP_SUCCESS';
export const CONSUMER_SIGNUP_FAILED = 'CONSUMER_SIGNUP_FAILED';