export const ALLPRODUCTS_SUCCESS = 'ALLPRODUCTS_SUCCESS';
export const ALLPRODUCTS_FAILED = 'ALLPRODUCTS_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';